<a href="https://colab.research.google.com/github/hyunicecream/Natural-Language-Processing-NLP-/blob/main/7_21_%EC%88%98(FastText_%EC%8B%A4%EC%8A%B5%26%EC%9E%90%EB%AA%A8%EB%8B%A8%EC%9C%84_%EB%B6%84%EB%A6%AC).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

Wed Jul 21 06:48:52 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   32C    P0    24W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [24]:
from gensim.models.fasttext import FastText
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import pickle
from gensim.test.utils import datapath

with open('/content/drive/MyDrive/머신러닝/자연어/konovel_preprocessed.pkl', 'rb') as f:
    texts = pickle.load(f)


In [25]:
#FastText 모델생성
model = FastText(size=100, window=5, min_count=10, sentences=texts,
                 max_vocab_size = 10000, sample=1e-5, iter=100, bucket=2000000,
                 sg=1, negative=2) # AWS server에서 실행시 : size =vector_size, iter = epochs

In [14]:
# 워드 벡터 확인
model.wv['환자']

array([ 5.60062788e-02, -3.34816039e-01,  5.94290942e-02,  3.19085941e-02,
        1.25433907e-01,  3.91396619e-02, -2.57090390e-01,  9.22845379e-02,
       -7.27408915e-04,  2.39125043e-01, -2.82891411e-02,  8.55770614e-03,
        7.92133436e-02, -2.22232267e-01,  4.08042729e-01,  1.73059404e-01,
        1.45881563e-01, -2.75996029e-01,  2.04898357e-01,  7.72694349e-02,
       -1.13667853e-01,  8.25333446e-02, -1.67100951e-01, -8.12288523e-02,
       -1.00178383e-01,  2.46292710e-01,  9.30687785e-02,  1.02451675e-01,
        9.94756669e-02,  2.83035263e-02, -1.03235230e-01, -3.29133719e-01,
        2.85318285e-01, -2.70792050e-04, -1.40035540e-01,  3.80081445e-01,
        1.78543292e-02,  9.00995806e-02,  5.44803888e-02, -1.11825407e-01,
       -1.86540671e-02,  6.79493994e-02, -1.80591494e-02, -1.43368870e-01,
        7.72553757e-02,  5.22249788e-02, -3.40290219e-01,  1.09369159e-01,
        8.83601755e-02,  4.79683876e-02,  4.90972139e-02,  1.79076344e-01,
       -2.06930395e-02, -

In [15]:
# oov라도 다른 벡터를 갖는다
model.wv['환자아아아아']
model.wv['아아환아아아아']

array([-7.05392100e-04,  2.24707220e-02,  1.76529467e-01, -1.99008316e-01,
        1.43350378e-01,  1.52836353e-01, -2.01396629e-01, -6.01888746e-02,
       -9.61645916e-02,  8.06536153e-02, -1.18295878e-01,  1.66219875e-01,
       -4.19775024e-02, -2.26846665e-01,  3.60008299e-01, -1.75977424e-02,
       -3.34592275e-02,  6.94898888e-02,  9.81177241e-02,  2.80541718e-01,
        1.62755862e-01, -1.22326836e-01,  1.73201144e-01, -8.35999548e-02,
        1.33363038e-01,  1.62536534e-03, -1.86680481e-01,  8.49706531e-02,
        1.39293626e-01,  1.74215645e-01,  1.60014465e-01, -2.91250348e-02,
        1.08170450e-01, -2.47521289e-02, -9.22309514e-03,  2.39535302e-01,
       -1.45361617e-01,  1.24265105e-01, -5.11166379e-02,  2.10975364e-01,
        2.38758579e-01,  5.21317869e-02, -1.28805101e-01,  1.13008291e-01,
       -1.30400389e-01,  5.29677458e-02, -1.63595062e-02,  1.58612549e-01,
       -2.65307605e-01,  6.52815700e-02,  9.08780321e-02,  3.50674331e-01,
        1.21585801e-01, -

In [16]:
# 유사도 확인
model.wv.most_similar('의사', topn=5)
model.wv.most_similar('엄마', topn=5)
model.wv.most_similar('딸', topn=5)
model.wv.most_similar('아버지', topn=5)
model.wv.most_similar('바다', topn=10)

[('바다로', 0.851055920124054),
 ('선착장', 0.8434188961982727),
 ('하늘', 0.8159232139587402),
 ('수평선', 0.8024173974990845),
 ('눈부시다', 0.7905569076538086),
 ('갈매기', 0.7811887264251709),
 ('물결', 0.7708677053451538),
 ('바닷가', 0.7671460509300232),
 ('반짝이다', 0.7651426792144775),
 ('벌판', 0.7605469226837158)]

In [18]:
# 어휘 사전 확인
model.wv.vocab['하늘']

In [19]:
# hash table (bucket) 확인. subword들의 워드 벡터가 저장된 공간.
model.wv.vectors_ngrams

array([[-0.02745507,  0.01891487, -0.10038022, ...,  0.1599825 ,
         0.07976013,  0.01991663],
       [-0.20020485, -0.44523224, -0.11662774, ..., -1.3191667 ,
         0.03792242,  0.87206334],
       [-0.01574848,  0.02621582, -0.09267586, ...,  0.16226277,
         0.07289371,  0.01676827],
       ...,
       [-0.08934738, -0.19028962, -0.00559302, ...,  0.12613657,
        -0.17979205,  0.13521682],
       [-0.084598  , -0.19136903, -0.01057228, ...,  0.12440763,
        -0.19329983,  0.14673616],
       [-0.09921796, -0.18071955, -0.00460855, ...,  0.11411124,
        -0.18573746,  0.1468723 ]], dtype=float32)

In [39]:
with open('/content/drive/MyDrive/머신러닝/자연어/konovel_preprocessed.pkl', 'wb') as f:
    pickle.dump(sentence_list, f, pickle.DEFAULT_PROTOCOL)

In [20]:
!pip install hangul_utils

  Created wheel for hangul-utils: filename=hangul_utils-0.2-py3-none-any.whl size=3265 sha256=21389389705be71a2a36db5627d39b47a217748fcf7e87bdfa9ebb082b000d8d
  Stored in directory: /root/.cache/pip/wheels/a6/f8/c9/96d021e59afdd738900b2a9efe97b2f216a2165ea4a0c7633f
Successfully built hangul-utils


In [42]:
# FastText 예시 : 한글을 자모 단위로 분리해서 FastText로 임베딩한다.
#
# 코드 구현 : blog.naver.com/chunjein, 2021.03.23
# pip install hangul_utils
#--------------------------------------------------------
from hangul_utils import split_syllables, join_jamos
from gensim.models.fasttext import FastText
import numpy as np
import pickle

In [43]:
# 한글 자모 분리/합침 연습
jamo = split_syllables('안녕하세요')
word = join_jamos(jamo)
print(jamo)

ㅇㅏㄴㄴㅕㅇㅎㅏㅅㅔㅇㅛ


In [44]:
from gensim.models.fasttext import FastText
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import pickle
from gensim.test.utils import datapath

with open('/content/drive/MyDrive/머신러닝/자연어/konovel_preprocessed.pkl', 'rb') as f:
    sent_list = pickle.load(f)


In [45]:
#FastText 모델생성
model = FastText(size=100, window=5, min_count=10, sentences=sent_list,
                 max_vocab_size = 10000, sample=1e-5, iter=100, bucket=2000000, min_n=3, max_n=3,
                 sg=1, negative=2) # AWS server에서 실행시 : size =vector_size, iter = epochs

In [46]:
sent_list[0]

['학교', '돌아오다', '욕실', '뛰어가다', '물', '뒤지다', '쓰다', '나오다', '비누', '냄새', '나다']

In [48]:
# sentence_list를 한글 자모로 분리한다.
sentence_jamo = []
for sentence in sent_list:
    jamo = []
    for word in sentence:
        jamo.append(split_syllables(word))
    sentence_jamo.append(jamo)

sentence_jamo[0]

['ㅎㅏㄱㄱㅛ',
 'ㄷㅗㄹㅇㅏㅇㅗㄷㅏ',
 'ㅇㅛㄱㅅㅣㄹ',
 'ㄸㅟㅇㅓㄱㅏㄷㅏ',
 'ㅁㅜㄹ',
 'ㄷㅟㅈㅣㄷㅏ',
 'ㅆㅡㄷㅏ',
 'ㄴㅏㅇㅗㄷㅏ',
 'ㅂㅣㄴㅜ',
 'ㄴㅐㅁㅅㅐ',
 'ㄴㅏㄷㅏ']

In [49]:
model = FastText(size=100, window=5, min_count=10, sentences=sentence_jamo, 
                 max_vocab_size=10000, sample=1e-5, iter=100, bucket=2000000, sg=1, negative=2)

def get_word_vector(model, word):
    jamo = split_syllables(word)
    return model.wv[jamo]

def get_similar_words(model, word, top_n=10):
    jamo = split_syllables(word)
    sim = []
    for (jamo, score) in model.wv.most_similar(jamo, topn = top_n):
        sim.append((join_jamos(jamo), score))
    return sim

# 어휘 사전 확인
model.wv.vocab

get_word_vector(model, '학교')

get_similar_words(model, '바다')

[('바다로', 0.8555504083633423),
 ('바닷가', 0.8470731973648071),
 ('바라다', 0.7918623685836792),
 ('타다', 0.7626050710678101),
 ('바닷물', 0.7484769821166992),
 ('밝다', 0.7325817942619324),
 ('밟다', 0.7180566787719727),
 ('바닥', 0.7088634967803955),
 ('흘러가다', 0.7082409858703613),
 ('바뀌다', 0.7013784646987915)]

In [47]:
# 유사도 확인
model.wv.most_similar('바다', topn=10)

[('바다로', 0.8551251292228699),
 ('수평선', 0.7668206691741943),
 ('소나기', 0.7598968744277954),
 ('하늘', 0.74162757396698),
 ('햇빛', 0.7397393584251404),
 ('물결', 0.7395631074905396),
 ('구름', 0.7356809377670288),
 ('갈매기', 0.7206027507781982),
 ('수풀', 0.7174332141876221),
 ('둥둥', 0.7126516699790955)]

In [40]:
with open('/content/drive/MyDrive/머신러닝/자연어/konovel_preprocessed.pkl', 'wb') as f:
    pickle.dump(sentence_list, f, pickle.DEFAULT_PROTOCOL)

In [ ]:
<Before> : 한글 자모 단위로 분리x
[('바다로', 0.851055920124054),
 ('선착장', 0.8434188961982727),
 ('하늘', 0.8159232139587402),
 ('수평선', 0.8024173974990845),
 ('눈부시다', 0.7905569076538086),
 ('갈매기', 0.7811887264251709),
 ('물결', 0.7708677053451538),
 ('바닷가', 0.7671460509300232),
 ('반짝이다', 0.7651426792144775),
 ('벌판', 0.7605469226837158)]
 <After> : 한글 자모 단위로 분리o
 [('수평선', 0.8704897165298462),
 ('바다로', 0.8318359851837158),
 ('선착장', 0.8157389163970947),
 ('물결', 0.7963809967041016),
 ('둥둥', 0.7877790331840515),
 ('수풀', 0.7865880727767944),
 ('하늘', 0.7838190197944641),
 ('갈매기', 0.7770141363143921),
 ('뭍', 0.774156928062439),
 ('눈부시다', 0.7594777345657349)]