<a href="https://colab.research.google.com/github/hyunicecream/Natural-Language-Processing-NLP-/blob/main/7_5_%EC%9B%94(%EC%B9%B4%EC%9A%B4%ED%8A%B8_%EA%B8%B0%EB%B0%98%EB%B0%A9%EB%B2%95Co_occurrence_matrix).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

docs = ['성진과 창욱은 야구장에 갔다',
        '성진과 태균은 도서관에 갔다',
        '성진과 창욱은 공부를 좋아한다']


count_model = CountVectorizer(ngram_range=(1,1))
x = count_model.fit_transform(docs)

In [19]:
print(count_model.vocabulary_)

{'성진과': 3, '창욱은': 6, '야구장에': 4, '갔다': 0, '태균은': 7, '도서관에': 2, '공부를': 1, '좋아한다': 5}


In [20]:
print(x)

  (0, 3)	1
  (0, 6)	1
  (0, 4)	1
  (0, 0)	1
  (1, 3)	1
  (1, 0)	1
  (1, 7)	1
  (1, 2)	1
  (2, 3)	1
  (2, 6)	1
  (2, 1)	1
  (2, 5)	1


In [21]:
print(x.toarray())
print()
print(x.T.toarray())

[[1 0 0 1 1 0 1 0]
 [1 0 1 1 0 0 0 1]
 [0 1 0 1 0 1 1 0]]

[[1 1 0]
 [0 0 1]
 [0 1 0]
 [1 1 1]
 [1 0 0]
 [0 0 1]
 [1 0 1]
 [0 1 0]]


In [23]:
xc = x.T * x
xc.setdiag(0)
print(xc.toarray())

[[0 0 1 2 1 0 1 1]
 [0 0 0 1 0 1 1 0]
 [1 0 0 1 0 0 0 1]
 [2 1 1 0 1 1 2 1]
 [1 0 0 1 0 0 1 0]
 [0 1 0 1 0 0 1 0]
 [1 1 0 2 1 1 0 0]
 [1 0 1 1 0 0 0 0]]


In [25]:
count_model = CountVectorizer(ngram_range=(1,2))
x = count_model.fit_transform(docs)
print(count_model.vocabulary_)s

{'성진과': 5, '창욱은': 11, '야구장에': 8, '갔다': 0, '성진과 창욱은': 6, '창욱은 야구장에': 13, '야구장에 갔다': 9, '태균은': 14, '도서관에': 3, '성진과 태균은': 7, '태균은 도서관에': 15, '도서관에 갔다': 4, '공부를': 1, '좋아한다': 10, '창욱은 공부를': 12, '공부를 좋아한다': 2}


In [27]:
xc = x.T * x 
xc.setdiag(0) 
print(xc.toarray())

[[0 0 0 1 1 2 1 1 1 1 0 1 0 1 1 1]
 [0 0 1 0 0 1 1 0 0 0 1 1 1 0 0 0]
 [0 1 0 0 0 1 1 0 0 0 1 1 1 0 0 0]
 [1 0 0 0 1 1 0 1 0 0 0 0 0 0 1 1]
 [1 0 0 1 0 1 0 1 0 0 0 0 0 0 1 1]
 [2 1 1 1 1 0 2 1 1 1 1 2 1 1 1 1]
 [1 1 1 0 0 2 0 0 1 1 1 2 1 1 0 0]
 [1 0 0 1 1 1 0 0 0 0 0 0 0 0 1 1]
 [1 0 0 0 0 1 1 0 0 1 0 1 0 1 0 0]
 [1 0 0 0 0 1 1 0 1 0 0 1 0 1 0 0]
 [0 1 1 0 0 1 1 0 0 0 0 1 1 0 0 0]
 [1 1 1 0 0 2 2 0 1 1 1 0 1 1 0 0]
 [0 1 1 0 0 1 1 0 0 0 1 1 0 0 0 0]
 [1 0 0 0 0 1 1 0 1 1 0 1 0 0 0 0]
 [1 0 0 1 1 1 0 1 0 0 0 0 0 0 0 1]
 [1 0 0 1 1 1 0 1 0 0 0 0 0 0 1 0]]
